declaraciones/api/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, re_path
from django.views.decorators.csrf import csrf_exempt
from rest_framework_simplejwt import views as jwt_views
from .views import LoginView, OauthDeclaraciones, estadisticasGraficasView, estadisticasView

urlpatterns = [
    path("v2/declaraciones/", csrf_exempt(OauthDeclaraciones.as_view())),
    path("token/", LoginView.as_view(), name='token_obtain_pair'),
    path("token/refresh/", jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path("estadisticas/", csrf_exempt(estadisticasView.as_view())),
    path("estadisticas-graficas/", estadisticasGraficasView, name='estadisticas-graficas'),
]

declaraciones/declaraciones/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.conf.urls import include, url
from declaracion import urls
from sitio import urls
from api import urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name ='reset_password'),  
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name ='password_reset_done'),  
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name ='password_reset_confirm'),  
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name ='password_reset_complete')
]

# front-edit
#urlpatterns += [
#    url(r'^front-edit/', include('front.urls')),
#]

admin.site.site_header = 'Administración de Declaraciones'
admin.site.site_title = 'Administración de Declaraciones'
admin.site.index_title =  'Bienvenido a la administración del sistema'

declaraciones/sitio/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views

from declaracion.views import PerfilView

from .views import (IndexView, LoginView, LogoutView, FAQView, DeclaracionesPreviasView, PasswordResetRFCView, 
                    DeclaracionesPreviasDescargarView, activar, CambioPasswordView, 
                    PersonalizacionCatalogoPuestosView,
                    PersonalizacionDatosEntidadView,
                    PersonalizacionCatalogoAreasView,
                    DeclaracionesPreviasVerView,
                    GenerarHTMLView,
                    consultaEstatusTaskPDFDeclaracion, crearPDFDeclaracion, eliminarProcesoPDF, PdfConfirmacion)

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('inicio', PerfilView.as_view(), name="inicio"),
    path('preguntas-frecuentes', FAQView.as_view(), name="preguntas-frecuentes"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('declaraciones-previas', DeclaracionesPreviasView.as_view(), name="declaraciones-previas"),
    re_path(r'^declaraciones-previas/descargar/(?P<folio>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})/$',
            DeclaracionesPreviasDescargarView.as_view(),
            name="declaraciones-previas-descargar"),
    re_path(r'^declaraciones-previas/ver/(?P<folio>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})/$',
            DeclaracionesPreviasVerView.as_view(),
            name="declaraciones-previas-ver"),
    url(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activar, name='activar'),
    path('cambiar', CambioPasswordView.as_view(), name="cambiar"),
    path('recuperar', LogoutView.as_view(), name="recuperar"),
    path('password_reset/', PasswordResetRFCView.as_view(success_url=reverse_lazy('password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('personalizar/catalogos/puestos', PersonalizacionCatalogoPuestosView.as_view(), name='personalizar_catpuestos'),
    path('personalizar/catalogos/puestos/agregar', PersonalizacionCatalogoPuestosView.as_view(), name='personalizar_catpuestos_agregar'),
    path('personalizar/catalogos/puestos/editar-<slug:pkid>', PersonalizacionCatalogoPuestosView.as_view(), name='personalizar_catpuestos_editar'),
    path('personalizar/catalogos/puestos/eliminar-<int:pkid>', PersonalizacionCatalogoPuestosView.as_view(), name='personalizar_catpuestos_eliminar'),

    path('personalizar/catalogos/areas', PersonalizacionCatalogoAreasView.as_view(), name='personalizar_catareas'),
    path('personalizar/catalogos/areas/agregar', PersonalizacionCatalogoAreasView.as_view(), name='personalizar_catareas_agregar'),
    path('personalizar/catalogos/areas/editar-<slug:pkid>', PersonalizacionCatalogoAreasView.as_view(), name='personalizar_catareas_editar'),
    path('personalizar/catalogos/areas/eliminar-<int:pkid>', PersonalizacionCatalogoAreasView.as_view(), name='personalizar_catareas_eliminar'),

    path('personalizar/datos_entidad', PersonalizacionDatosEntidadView.as_view(), name='personalizar_entidad'),
    path('personalizar/datos_entidad/editar', PersonalizacionDatosEntidadView.as_view(), name='personalizar_entidad_editar'),
   
    path('generar_html', GenerarHTMLView, name='generar_html'),
    url(r'^declaraciones-previas/estatus_pdf_declaracion/$', consultaEstatusTaskPDFDeclaracion, name='estatus_pdf_declaracion'),
    url(r'^declaraciones-previas/crear_pdf_declaracion/$', crearPDFDeclaracion, name='crear_pdf_declaracion'),
    url(r'^declaraciones-previas/eliminar_pdf_declaracion/$', eliminarProcesoPDF, name='eliminar_pdf_declaracion'),
	path('pdf_confimacion/<int:pk>/', PdfConfirmacion.as_view(), name="pdf_confimacion"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

declaraciones/sitio/models.py
from django.db import models
from colorfield.fields import ColorField


class sitio_personalizacion(models.Model):
	"""
	Class modelo sitio_personalizacion integrado para realizar cambios en el diseño del sistema como logo y colores
	"""
	nombre_institucion = models.CharField("Nombre de la institución", max_length=300, default="Sin nombrar")
	siglas_sistema = models.CharField("Siglas del sistema", max_length=30, default="SN")
	direccion_calle = models.CharField("Calle, número y numero interior de la institución", max_length=300, default="Sin nombrar")
	direccion_cp = models.CharField("código postal de la institución", max_length=300, default="Sin nombrar")
	direccion_ciudad = models.CharField("ciudad de la institución", max_length=300, default="Sin nombrar")
	direccion_estado = models.CharField("estado de la institución", max_length=300, default="Jalisco")
	direccion_telefonos = models.CharField("telefonos de la institución", max_length=300, default="sn")
	direccion_correos = models.CharField("correos electrónico de la institución", max_length=300, default="sn")
	#activar_captcha = models.BooleanField("Activar o desactivar los captcha (necesitas haber dado de alta una llave correcta en el campo 'llave para el captcha de google')", default=False)
	recaptcha = models.BooleanField(default=False)
	google_captcha_sitekey = models.CharField("Clave sitio web para el captcha de Google ", max_length=300, default="6LdVTt0UAAAAAEkz8C_gBLX8F4O4cJZt762TDgvW")
	google_captcha_secretkey = models.CharField("Clave secreta captcha de Google ", max_length=300, null=True, blank=True)
	terminosCondiciones_registro = models.FileField("PDF con los terminos y condiciones al registrarse", upload_to='personalizar/', max_length=300, default='personalizar/terminos_y_Condiciones_registro.pdf')
	imagen_logo = models.ImageField("imagen logo", upload_to='personalizar/', max_length=300, default='personalizar/default_logo.png')
	imagen_sublogo = models.ImageField("imagen logo simplificado ", upload_to='personalizar/', max_length=300, default='personalizar/default_logo_simple.png')
	imagen_inicioFondo = models.ImageField("imagen fondo del index", upload_to='personalizar/', max_length=300, default='personalizar/default_fondo_index.png')
	imagen_inicioPiepagina = models.ImageField("imagen pie de página del index", upload_to='personalizar/', max_length=300, default='personalizar/default_footer_index.png')
	imagen_defaultPerfil = models.ImageField("imagen default para el perfil de usuario", upload_to='personalizar/', max_length=300, default='personalizar/default_image_perfil.png')
	color_base = models.CharField("Color base (default=#fff)", max_length=20, default="#fff")
	color_obscuro = models.CharField("Color obscuro (default=#000)", max_length=20, default="#000")
	color_primario = models.CharField("Color primario (default=#015F78)", max_length=20, default="#015F78")
	color_secundario = models.CharField("Color secundario (default=#A4B54C)", max_length=20, default="#A4B54C")
	color_neutro = models.CharField("Color neutro (default=#F2F2F2)", max_length=20, default="#F2F2F2")
	color_suceso = models.CharField("Color suceso (default=#5dffff)", max_length=20, default="#5dffff")
	color_peligro = models.CharField("Color peligro (default=#38A6F9)", max_length=20, default="#38A6F9")
	color_alerta = models.CharField("Color error (default=#dc3545)", max_length=20, default="#dc3545")
	fecha_incio = models.DateField(null=True)
	fecha_fin = models.DateField(null=True)
	declaracion_modificacion_crear = models.BooleanField("Crear declaración de modificación de manera abierta", default=True)

	class Meta:
		verbose_name = 'personalización del sitio'
		verbose_name_plural = 'personalización del sitio'

	def __str__(self):
		return self.nombre_institucion


class declaracion_faqs(models.Model):
	orden = models.IntegerField("Orden (si tiene cero es omitido)", blank=False, default=0)
	pregunta = models.CharField("Pregunta", max_length=3000, default="")
	respuesta = models.CharField("Respuesta", max_length=3000, default="")

	class Meta:
		verbose_name = "Preguntas Frecuentes sobre declaraciones"
		verbose_name_plural = "Preguntas Frecuentes sobre declaraciones"

	def __str__(self):
		return self.pregunta


class Valores_SMTP(models.Model):

	mailaddress = models.CharField("Correo", max_length=300)
	mailpassword = models.CharField("Contraseña", max_length=200)
	nombre_smtp = models.CharField("SMTP", max_length=200)
	puerto = models.IntegerField("Puerto", blank=False)

	def __str__(self):
		return "SMTP "+str(self.pk)		

declaraciones/sitio/forms.py
from django import forms
from django.contrib.auth.models import User
from django.template import loader
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import authenticate, login, logout,get_user_model,password_validation
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
import datetime


UserModel = get_user_model()

class PasswordResetForm(forms.Form):
    rfc = forms.CharField(label="RFC", max_length=254)

    def send_mail(self, subject_template_name, email_template_name,context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)

            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

    def get_users(self, username):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = UserModel._default_manager.filter(**{
            'username__iexact':  username,
            'is_active': True,
        })
        return (u for u in active_users if u.has_usable_password())

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name='registration/password_reset_email.html',
             extra_email_context=None):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        rfc = self.cleaned_data["rfc"]
        tt = False
        for user in self.get_users(rfc):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name, email_template_name, context, from_email,
                user.email, html_email_template_name='registration/password_reset_email.html',
            )
            tt = True
        return tt



class LoginForm(forms.Form):

    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if User.objects.filter(username=username).count() ==0:
            self.add_error("username","RFC no registrado")
        else:
            user = User.objects.get(username=username)
            if user.is_active:
                user = authenticate(username=username, password=password)
                if not user or not user.is_active:
                    self.add_error("password", "Contraseña incorrecta")

            else:
                self.add_error("username", "Usuario inactivo, revisa tu correo y sigue las instrucciones para activar tu usuario")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class Personalizar_datosEntidadForm(forms.Form):
    """
        Formulario para editar los datos de la entidad 
    """
    nombre_institucion = forms.CharField(label="Nombre de la entidad", max_length=300)
    siglas_sistema = forms.CharField(label="Siglas del sistema", max_length=30)
    direccion_calle = forms.CharField(label="Calle, número y numero interior de la entidad", max_length=300)
    direccion_cp = forms.CharField(label="código postal de la entidad", max_length=300)
    direccion_ciudad = forms.CharField(label="ciudad de la entidad", max_length=300)
    direccion_estado = forms.CharField(label="estado de la entidad", max_length=300)
    direccion_telefonos = forms.CharField(label="telefono de la entidad", max_length=300)
    direccion_correos = forms.CharField(label="correos electrónico de la entidad", max_length=300)
    #activar_captcha = forms.BooleanField(label="Activar o desactivar los captcha (necesitas haber dado de alta una llave correcta en el campo 'llave para el captcha de google')",)
    google_captcha_sitekey = forms.CharField(label="Clave sitio web para el captcha de Google ", max_length=300)
    google_captcha_secretkey = forms.CharField(label="Clave secreta captcha de Google ", max_length=300,)
    terminosCondiciones_registro = forms.FileField(label="PDF con los terminos y condiciones al registrarse")
    imagen_logo = forms.ImageField(label="imagen logo")
    imagen_sublogo = forms.ImageField(label="imagen logo simplificado ")
    imagen_inicioFondo = forms.ImageField(label="imagen fondo del index")
    imagen_inicioPiepagina = forms.ImageField(label="imagen pie de página del index")
    imagen_defaultPerfil = forms.ImageField(label="imagen default para el perfil de usuario")

    def clean(self):
        super().clean()

declaraciones/templates/sitio/cambio-password.html
{% extends "layout/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block header_title %}Preguntas Frecuentes{% endblock %}
{% block content %}
<section>
  <div class="container-fluid mt-4">
    <div class="row">
      <div class="col-xs-0 col-sm-0 col-md-0 col-lg-2 col-xl-2">
      </div>
      <div class="col-xs-auto col-sm-auto col-md-auto mt-5 caja">

      </div>
      <div class="col-xs-11 col-sm-11 col-md-7 mt-2">
      	<p class="Ingresa-al-sistema mt-5 mb-1">INGRESA AL SISTEMA</p>
      	<p class="Escribe-tus-datos-por-favor">Escribe tus datos por favor {{ user.first_name }} {{ user.last_name }}</p>
      	<form action="{% url 'cambiar' %}" method="post">
            {% csrf_token %}
            {% if messages %}
                {% for message in messages %}

                        {% if message.tags == "success" %}
                            <div class="alert alert-success alert-dismissable alert-link">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                 <strong>{{ message }}</strong>
                            </div>
                        {% endif %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissable alert-link">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                 <strong>{{ message }}</strong>
                            </div>
                        {% endif %}


                {% endfor %}
            {% endif %}

            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary mt-4"  >CAMBIAR</button>
              <!--p class="Olvidaste-tu-contrasea mt-3"><a href="{% url 'recuperar' %}" class="text-reset" data-toggle="modal" data-target="#ventana-modal" data-whatever="@mdo">¿Olvidaste tu contraseña?</a></p-->
             <!-- <p class="An-no-tienes-cuenta-Crear-cuenta">¿Aún no tienes cuenta? <span class="texto-Crear-Cuenta">Crear cuenta</span></p>-->
        </form>
       </div>
      <div class="col-xs-1 col-sm-1 col-md-2">
      </div>
  </div>
</div>
 </section>
 <div style="height:500px;">
</div>

<!-- Ventana modal para recuperar la contraseña con RFC como Homoclave  -->
<div class="modal fade" id="ventana-modal" tabindex="-1" role="dialog" aria-labelledby="lost-password-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close text-base" data-dismiss="modal" aria-label="Close">CERRAR
          <img src="{% static 'src/img/close.svg' %}" alt="Cerrar" class="svg">
        </button>
        <h3 class="modal-title mt-5 mb-3 text-lg text-uppercase font-weight-normal" id="lost-password-label">Para recuperar tu contraseña escribe tu <span class="text-black">RFC con homoclave</span> por favor</h3>
        <form action="{% url 'password_reset' %}" method="post" id="form_reset" class="mb-2">
          {% csrf_token %}
          <div class="form-group valida_rfc " id="rec-rfc">
            <input type="text" class="form-control bg-transparent" id="id_rfc_rs" name="rfc" placeholder="RFC con homoclave" required autofocus>
          </div>
        </form>
        <p class="text-success-lighter text-md">Si desconoces tu RFC o necesitas cambiarlo ponte en contacto con el enlace de tu ente público.</p>
        <div class="text-right">
          <button type="button" class="btn btn-primary font-weight-semibold" id="recuperar">Enviar</button>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Ventana modal despues de que el usuario ya escribio el RFC como homoclave  -->
<div class="modal fade" id="modal-recuperar-contrasena" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title mt-5" id="modal-recuperar-contraseña"></p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="cerrar-modal"><p style="font-size: 16px;">CERRAR &nbsp; <img src="/static/src/img/cerrar.png"width="18" height="18" alt="" class="svg" style=" float: right"></p></span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group text-center">
            <p class="text-primary">¡MUCHAS GRACIAS!</p>
            <p>Hemos envíado a tu correo las<br>instrucciones para reestablecer<br>la contraseña.</p>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>



{% endblock %}

declaraciones/templates/sitio/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load personalizacion_tags %}
{% block header_title %}Bienvenido(a){% endblock %}
{% block header_style %}
    <style rel="stylesheet" type="text/css" href="{% static 'index.css' %}"></style>
    <style>
        #index_bg {
            padding-bottom: 80px !important;
            padding-left: 10px !important;
        }
    </style>
{% endblock %}
{% block content_header %}
<div class="row container-fluid p-0 body_content" >
    <img id="index_bg" src="/media/{% personalizacion 'imagen_inicioFondo' %}" class="img-fluid fixed-bottom zi-a f-center m-center fit_to_body w-75 w-sm-100 pb-3" alt="index_background">
{% endblock %}
{% block content %}
        <div class="col-md-6 col-sm-12">
            {% if user.is_superuser %} 
            <a class="color-neutro" href="/admin/sitio/sitio_personalizacion/1/change/#id_imagen_logo" alt="Personalizar" target="_blank">
            <div class="w-100 personalizar_clic">
                <p class="color-alerta icono_personalizar"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                  </svg> Personalizar el sitio </p>
            {% else %}
            <a href="/">
            {% endif %}
            <img src="/media/{% personalizacion 'imagen_logo' %}" alt="logo" class="img-fluid index-logo p-3">
            {% if user.is_superuser %} </div> {% endif %}    
        </a>
        </div>
        <div class="col-md-6 col-sm-12 row mt-auto text-center index-div-options pt-10p">
            {% block opciones %}
            <div class="col-10 offset-2 ">
                <p class="color-secundario h1 font-weight-semibold"> Bienvenido</p>
                <p class="h3 font-weight-light"> Al sistema de declaraciones</p>
                <p class="h2">de</p>
                <p class="color-primario h1 font-weight-bold"> Jalisco</p>
            </div>
            <div class="col-12 row text-center">
                {% if not user.is_staff and not user.is_superuser %}
                <div class="col-4 offset-2">
                <a href="{% url 'declaracion:declaracion' %}" class="color-primario">
                  <figure class="text-center pr-2">
                  <img src="{% static 'src/img/SEAJAL-Declaraciones-Index-Hacer_declaracion.png' %}" alt="Realiza tu declaración" width="100px" class="img-responsive">
                  <figcaption> <strong> Realiza tu declaración </strong></figcaption>
                  </figure>
                </a>
              </div>
                {%endif%}
                {% if not user.is_authenticated %}
                <div class="col-4 offset-2">
                  <a href="{% url 'declaracion:nuevo' %}" class="color-primario">
                    <figure class="text-center pl-2">
                      <img src="{% static 'src/img/SEAJAL-Declaraciones-Index-Crear_cuenta.png' %}" alt="Crea tu cuenta" width="100px" class="img-responsive">
                      <figcaption> <strong>Crea tu cuenta </strong></figcaption>
                    </figure>
                  </a>
                  </div>
                  {% else %}
                  <div class="col-6 text-right">
                        <p>Tareas disponibles:</p>
                        {% if user.is_staff %}
                        <li>   
                            <a href="/declaracion/admin/busqueda-declaraciones" class="color-primario">
                                Buscar declaraciones
                            </a>
                        </li>
                        {% else %}
                        <li>   
                            <a href="/declaracion" class="color-primario">
                                Hacer una declaracion
                            </a>
                        </li>
                        <li>
                            <a class="color-primario" href="{% url 'declaraciones-previas' %}">
                                ver declaraciones previas
                            </a>
                        </li>
                        {% endif %}
                        {% if user.is_superuser %}
                        <li>
                            <a href="/admin/sitio/sitio_personalizacion/1/change/" class="color-primario">
                                Personalizar el sitio
                            </a>
                        </li>
                        {% endif %}
                      </ul>
                {% endif %}
              </div>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block content_footer %}
    <img class="img-fluid fixed-bottom index-img-footer f-center m-center fit_to_body w-100" src="/media/{% personalizacion 'imagen_inicioPiepagina' %}">
    <div class="version_sw">
        versión 001.200820
    </div>
{% endblock %}